version: "3.8"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: my_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB= hcode
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./conf/postgresql.conf:./etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U root -d hcode'",]
      interval: 10s
      timeout: 3s
      retries: 3
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      postgresql:
        condition: service_healthy