services:
  mariadb:
    image: mariadb:latest
    container_name: my_mariadb
    restart: always
    ports:
      - 3317:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d/my
  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mariadb