services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    restart: always
    ports:
      - 3316:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d/my